spring: 
  profiles: 
    active: 
    - dev
---
spring: 
    #开发环境
  profiles: dev
  application: 
    name: microservercloud-gen-dev
---
spring: 
    #测试环境
  profiles: test
  application: 
    name: microservercloud-gen-test
# 必须保存为UTF-8的格式, 否则会报一些未知错误!!