spring: 
  profiles: 
    active: 
    - dev
---
info: 
  app.name: gen-microservercloud-springcloudconfig02
  company.name: genshi
  build.artifactId: $project.artifactId$
  build.version: $project.version$
spring: 
  profiles: dev
  application:
    name: microservercloud-config-dept-client
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?useSSL=false&useUnicode=true
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
  instance: 
    instance-id: microservercloud-config-dept-dev8001 #定义服务实例名
    prefer-ip-address: true #访问路径可以显示ip
info: 
  app.name: gen-microservercloud-springcloudconfig02
  company.name: genshi
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
spring: 
  profiles: test
  application: 
    name: microservercloud-config-dept-client
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb02?useSSL=false&useUnicode=true
    username: root
    password: root
    dbcp2: 
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
  instance: 
    instance-id: microservercloud-config-dept-test8001 #定义服务实例名
    prefer-ip-address: true #访问路径可以显示ip
info: 
  app.name: gen-microservercloud-springcloudconfig02
  company.name: genshi
  build.artifactId: $project.artifactId$
  build.version: $project.version$