spring: 
  active: 
  - dev
---
server: 
  port: 8201
spring: 
  profiles: dev
  application: 
    name: microservercloud-config-client
eureka:
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
---
server: 
  port: 8202
spring: 
  profiles: test
  application: 
    name: microservercloud-config-client
eureka:
  client: 
    service-url: 
      defaultZone: http://eureka7002.com:7002/eureka/